//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAutokauppaApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/AutokauppaWCF")]
    [System.SerializableAttribute()]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMalliID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMerkkiID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Hinta1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mittarilukema1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Moottorin_tilavuus1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PolttoaineID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Rekisteri_paivamaara1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VaritID1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMalliID1 {
            get {
                return this.AutonMalliID1Field;
            }
            set {
                if ((this.AutonMalliID1Field.Equals(value) != true)) {
                    this.AutonMalliID1Field = value;
                    this.RaisePropertyChanged("AutonMalliID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMerkkiID1 {
            get {
                return this.AutonMerkkiID1Field;
            }
            set {
                if ((this.AutonMerkkiID1Field.Equals(value) != true)) {
                    this.AutonMerkkiID1Field = value;
                    this.RaisePropertyChanged("AutonMerkkiID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Hinta1 {
            get {
                return this.Hinta1Field;
            }
            set {
                if ((this.Hinta1Field.Equals(value) != true)) {
                    this.Hinta1Field = value;
                    this.RaisePropertyChanged("Hinta1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mittarilukema1 {
            get {
                return this.Mittarilukema1Field;
            }
            set {
                if ((this.Mittarilukema1Field.Equals(value) != true)) {
                    this.Mittarilukema1Field = value;
                    this.RaisePropertyChanged("Mittarilukema1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Moottorin_tilavuus1 {
            get {
                return this.Moottorin_tilavuus1Field;
            }
            set {
                if ((this.Moottorin_tilavuus1Field.Equals(value) != true)) {
                    this.Moottorin_tilavuus1Field = value;
                    this.RaisePropertyChanged("Moottorin_tilavuus1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolttoaineID1 {
            get {
                return this.PolttoaineID1Field;
            }
            set {
                if ((this.PolttoaineID1Field.Equals(value) != true)) {
                    this.PolttoaineID1Field = value;
                    this.RaisePropertyChanged("PolttoaineID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Rekisteri_paivamaara1 {
            get {
                return this.Rekisteri_paivamaara1Field;
            }
            set {
                if ((this.Rekisteri_paivamaara1Field.Equals(value) != true)) {
                    this.Rekisteri_paivamaara1Field = value;
                    this.RaisePropertyChanged("Rekisteri_paivamaara1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VaritID1 {
            get {
                return this.VaritID1Field;
            }
            set {
                if ((this.VaritID1Field.Equals(value) != true)) {
                    this.VaritID1Field = value;
                    this.RaisePropertyChanged("VaritID1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutonMerkki", Namespace="http://schemas.datacontract.org/2004/07/AutokauppaWCF")]
    [System.SerializableAttribute()]
    public partial class AutonMerkki : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Merkki1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Merkki1 {
            get {
                return this.Merkki1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Merkki1Field, value) != true)) {
                    this.Merkki1Field = value;
                    this.RaisePropertyChanged("Merkki1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutonMalli", Namespace="http://schemas.datacontract.org/2004/07/AutokauppaWCF")]
    [System.SerializableAttribute()]
    public partial class AutonMalli : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMerkkiID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Auton_mallin_nimi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMerkkiID1 {
            get {
                return this.AutonMerkkiID1Field;
            }
            set {
                if ((this.AutonMerkkiID1Field.Equals(value) != true)) {
                    this.AutonMerkkiID1Field = value;
                    this.RaisePropertyChanged("AutonMerkkiID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auton_mallin_nimi1 {
            get {
                return this.Auton_mallin_nimi1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Auton_mallin_nimi1Field, value) != true)) {
                    this.Auton_mallin_nimi1Field = value;
                    this.RaisePropertyChanged("Auton_mallin_nimi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Polttoaineet", Namespace="http://schemas.datacontract.org/2004/07/AutokauppaWCF")]
    [System.SerializableAttribute()]
    public partial class Polttoaineet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Polttoaineen_nimi1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Polttoaineen_nimi1 {
            get {
                return this.Polttoaineen_nimi1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Polttoaineen_nimi1Field, value) != true)) {
                    this.Polttoaineen_nimi1Field = value;
                    this.RaisePropertyChanged("Polttoaineen_nimi1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Varit", Namespace="http://schemas.datacontract.org/2004/07/AutokauppaWCF")]
    [System.SerializableAttribute()]
    public partial class Varit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Varin_nimi1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Varin_nimi1 {
            get {
                return this.Varin_nimi1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Varin_nimi1Field, value) != true)) {
                    this.Varin_nimi1Field = value;
                    this.RaisePropertyChanged("Varin_nimi1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDatabaseConnection", ReplyAction="http://tempuri.org/IService1/TestDatabaseConnectionResponse")]
        bool TestDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDatabaseConnection", ReplyAction="http://tempuri.org/IService1/TestDatabaseConnectionResponse")]
        System.Threading.Tasks.Task<bool> TestDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveAuto", ReplyAction="http://tempuri.org/IService1/saveAutoResponse")]
        bool saveAuto(WCFAutokauppaApp.ServiceReference1.Auto newAuto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveAuto", ReplyAction="http://tempuri.org/IService1/saveAutoResponse")]
        System.Threading.Tasks.Task<bool> saveAutoAsync(WCFAutokauppaApp.ServiceReference1.Auto newAuto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllAutoMakers", ReplyAction="http://tempuri.org/IService1/getAllAutoMakersResponse")]
        System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.AutonMerkki> getAllAutoMakers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllAutoMakers", ReplyAction="http://tempuri.org/IService1/getAllAutoMakersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.AutonMerkki>> getAllAutoMakersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAutoModels", ReplyAction="http://tempuri.org/IService1/getAutoModelsResponse")]
        System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.AutonMalli> getAutoModels(int makerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAutoModels", ReplyAction="http://tempuri.org/IService1/getAutoModelsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.AutonMalli>> getAutoModelsAsync(int makerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPolttoaine", ReplyAction="http://tempuri.org/IService1/GetPolttoaineResponse")]
        System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.Polttoaineet> GetPolttoaine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPolttoaine", ReplyAction="http://tempuri.org/IService1/GetPolttoaineResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.Polttoaineet>> GetPolttoaineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVari", ReplyAction="http://tempuri.org/IService1/GetVariResponse")]
        System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.Varit> GetVari();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVari", ReplyAction="http://tempuri.org/IService1/GetVariResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.Varit>> GetVariAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMinId", ReplyAction="http://tempuri.org/IService1/GetMinIdResponse")]
        int GetMinId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMinId", ReplyAction="http://tempuri.org/IService1/GetMinIdResponse")]
        System.Threading.Tasks.Task<int> GetMinIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaxId", ReplyAction="http://tempuri.org/IService1/GetMaxIdResponse")]
        int GetMaxId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaxId", ReplyAction="http://tempuri.org/IService1/GetMaxIdResponse")]
        System.Threading.Tasks.Task<int> GetMaxIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NextPrevAuto", ReplyAction="http://tempuri.org/IService1/NextPrevAutoResponse")]
        WCFAutokauppaApp.ServiceReference1.Auto NextPrevAuto(int autoId, bool next, bool prev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NextPrevAuto", ReplyAction="http://tempuri.org/IService1/NextPrevAutoResponse")]
        System.Threading.Tasks.Task<WCFAutokauppaApp.ServiceReference1.Auto> NextPrevAutoAsync(int autoId, bool next, bool prev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAuto", ReplyAction="http://tempuri.org/IService1/DeleteAutoResponse")]
        void DeleteAuto(int autoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAuto", ReplyAction="http://tempuri.org/IService1/DeleteAutoResponse")]
        System.Threading.Tasks.Task DeleteAutoAsync(int autoId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCFAutokauppaApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCFAutokauppaApp.ServiceReference1.IService1>, WCFAutokauppaApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TestDatabaseConnection() {
            return base.Channel.TestDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<bool> TestDatabaseConnectionAsync() {
            return base.Channel.TestDatabaseConnectionAsync();
        }
        
        public bool saveAuto(WCFAutokauppaApp.ServiceReference1.Auto newAuto) {
            return base.Channel.saveAuto(newAuto);
        }
        
        public System.Threading.Tasks.Task<bool> saveAutoAsync(WCFAutokauppaApp.ServiceReference1.Auto newAuto) {
            return base.Channel.saveAutoAsync(newAuto);
        }
        
        public System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.AutonMerkki> getAllAutoMakers() {
            return base.Channel.getAllAutoMakers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.AutonMerkki>> getAllAutoMakersAsync() {
            return base.Channel.getAllAutoMakersAsync();
        }
        
        public System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.AutonMalli> getAutoModels(int makerId) {
            return base.Channel.getAutoModels(makerId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.AutonMalli>> getAutoModelsAsync(int makerId) {
            return base.Channel.getAutoModelsAsync(makerId);
        }
        
        public System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.Polttoaineet> GetPolttoaine() {
            return base.Channel.GetPolttoaine();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.Polttoaineet>> GetPolttoaineAsync() {
            return base.Channel.GetPolttoaineAsync();
        }
        
        public System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.Varit> GetVari() {
            return base.Channel.GetVari();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCFAutokauppaApp.ServiceReference1.Varit>> GetVariAsync() {
            return base.Channel.GetVariAsync();
        }
        
        public int GetMinId() {
            return base.Channel.GetMinId();
        }
        
        public System.Threading.Tasks.Task<int> GetMinIdAsync() {
            return base.Channel.GetMinIdAsync();
        }
        
        public int GetMaxId() {
            return base.Channel.GetMaxId();
        }
        
        public System.Threading.Tasks.Task<int> GetMaxIdAsync() {
            return base.Channel.GetMaxIdAsync();
        }
        
        public WCFAutokauppaApp.ServiceReference1.Auto NextPrevAuto(int autoId, bool next, bool prev) {
            return base.Channel.NextPrevAuto(autoId, next, prev);
        }
        
        public System.Threading.Tasks.Task<WCFAutokauppaApp.ServiceReference1.Auto> NextPrevAutoAsync(int autoId, bool next, bool prev) {
            return base.Channel.NextPrevAutoAsync(autoId, next, prev);
        }
        
        public void DeleteAuto(int autoId) {
            base.Channel.DeleteAuto(autoId);
        }
        
        public System.Threading.Tasks.Task DeleteAutoAsync(int autoId) {
            return base.Channel.DeleteAutoAsync(autoId);
        }
    }
}
